name = "DummyApp"
uuid = "26cc642e-2568-430c-a97a-1f3abe55fcde"
authors = ["jeremie.db <jeremie.db@evovest.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"

[compat]
CSV = "0.10"
julia = "1.9"